### ISSUE TITLE
Reccomended way to get setup w/ a fabric server with this tool

### ISSUE THREAD

**Issue by jasikpark** [Tom-The-Geek/pack-it#1]
This looks great! I've been looking for a tool that would function similar to yarn or cargo for managing my Minecraft server, I'm just on a machine that I've got ssh access to, so I've just been `curl`ing the mods into `mods/`, but I really wanted a way to specify the versions w/ an easy way to upgrade!

2 Questions:
- How do I upgrade versions? Do I run the "add this mod" step again, and it'll look for the newest version? Or do I need to do something else?

**Comment by Tom-The-Geek** [comment]
In the future, there will be a command to update all mods automatically, but for now, yes, rerunning the add command will update them to the latest version

**Comment by jasikpark** [comment]
Hmm I'm getting 
```sh
pack-it curseforge-add fabric-api
ℹ️  Resolving fabric-api...
⚠️  No compatible version found for fabric-api!
```
for 
```toml
pack_name = "pack-it test"
author = ""
accepted_game_versions = ["1.17.1","1.17"]
mod_loader = "Fabric"

[installed_mods]
```
